---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group these two modules together for pull requests
      # "pipeline-submodules" is an arbitrary name
      pipeline-submodules:
        patterns:
          - "*/pipeline-Nextflow-config"
          - "*/pipeline-Nextflow-module"
