---
algorithm:
  type: 'List'
  required: true
  help: 'List of sSNV algorithms'
  default:
    - mutect2
    - somaticsniper
    - strelka2
    - muse
  choices:
    - mutect2
    - somaticsniper
    - strelka2
    - muse
reference:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Absolute path to reference directory'
intersect_regions:
  type: 'Path'
  required: true
  help: 'call regions bed file used by mutect2, strelka2 and intersect'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to output directory'
work_dir:
  type: 'Path'
  mode: 'w'
  required: false
  help: 'Absolute path to output directory'
dataset_id:
  type: 'String'
  required: true
  help: 'Dataset identifier'
exome:
  type: 'Bool'
  required: false
  default: false
  help: 'The exome option when running manta and strelka2'
save_intermediate_files:
  type: 'Bool'
  required: false
  default: false
  help: 'The option to save the intermediate files'
bgzip_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for bgzip command'
tabix_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for tabix command'
split_intervals_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the SplitIntervals command'
mutect2_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the Mutect2 command'
filter_mutect_calls_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the FilterMutectCalls command'
scatter_count:
  type: 'Integer'
  required: true
germline_resource_gnomad_vcf:
  type: 'Path'
  required: false
  allow_empty: true
dbSNP:
  type: 'Path'
  required: true
ncbi_build:
  type: 'String'
  required: true
  help: 'NCBI build version, e.g. GRCh38'
vcf2maf_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the vcf2maf command'
patient_id:
  type: 'String'
  required: true
  help: 'Patient identifier'
base_resource_update:
  type: 'ResourceUpdateNamespace'
  required: false
  help: 'User-defined modifications for adjusting base resource allocations for processes'
  elements:
    memory:
      type: 'ResourceUpdateList'
      required: false
      help: 'List of memory updates'
    cpus:
      type: 'ResourceUpdateList'
      required: false
      help: 'List of CPU updates'
input:
  type: 'InputNamespace'
  required: true
  help: 'Input to process'
  elements:
    tumor:
      type: 'BAMEntryList'
      required: false
      help: 'Tumor id/path input'
      elements:
        BAM:
          type: 'Path'
          mode: 'r'
          required: true
          help: 'Absolute path to tumor sample BAM files'
        contamination_table:
          type: 'Path'
          mode: 'r'
          required: false
          help: 'Absolute path to contamination.tables'
    normal:
      type: 'BAMEntryList'
      required: false
      help: 'Normal id/path input'
      elements:
        BAM:
          type: 'Path'
          mode: 'r'
          required: true
          help: 'Absolute path to normal sample BAM files'
    muse:
      type: 'Path'
      mode: 'r'
      required: false
      help: 'Absolute path to muse VCF file'
    mutect2:
      type: 'Path'
      mode: 'r'
      required: false
      help: 'Absolute path to mutect2 VCF file'
    somaticsniper:
      type: 'Path'
      mode: 'r'
      required: false
      help: 'Absolute path to somaticsniper VCF file'
    strelka2:
      type: 'Path'
      mode: 'r'
      required: false
      help: 'Absolute path to strelka2 VCF file'
