---
algorithm:
  type: 'List'
  required: true
  help: 'List of sSNV algorithms'
  default:
    - mutect2
    - somaticsniper
    - strelka2
    - muse
  choices:
    - mutect2
    - somaticsniper
    - strelka2
    - muse
reference:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Absolute path to reference directory'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to output directory'
work_dir:
  type: 'Path'
  mode: 'w'
  required: false
  help: 'Absolute path to output directory'
patient_id:
  type: 'String'
  required: true
  help: 'Patient identifier'
dataset_id:
  type: 'String'
  required: true
  help: 'Dataset identifier'
save_intermediate_files:
  type: 'Bool'
  required: true
  default: false
  help: 'The option to save the intermediate files'
exome:
  type: 'Bool'
  required: false
  default: false
  help: 'The exome option when running manta and strelka2'
call_region:
  type: 'Path'
  required: false
  default: '/hot/ref/tool-specific-input/Strelka2/GRCh38/strelka2_call_region.bed.gz'
  help: 'A call region bed file for strelka2 to save runtime or for a targeted region'
split_intervals_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the SplitIntervals command'
mutect2_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the Mutect2 command'
filter_mutect_calls_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the FilterMutectCalls command'
scatter_count:
  type: 'Integer'
  required: true
  default: 50
intervals:
  type: 'String'
  required: false
  allow_empty: true
  help: 'A GATK accepted interval list file'
germline_resource_gnomad_vcf:
  type: 'Path'
  required: false
  allow_empty: true
input:
  type: 'InputNamespace'
  required: true
  help: 'Input samples'
  elements:
    tumor:
      type: 'List'
      required: true
      help: 'Tumor id/path input'
      elements:
        id:
          type: 'String'
          mode: 'r'
          required: true
          help: 'Tumor sample id will be used for filenames'
        BAM:
          type: 'Path'
          mode: 'r'
          required: true
          help: 'Absolute path to tumor sample BAM files'
    normal:
      type: 'List'
      required: false
      help: 'Normal id/path input'
      elements:
        id:
          type: 'String'
          mode: 'r'
          required: false
          help: 'Normal sample id will be used for filenames'
        BAM:
          type: 'Path'
          mode: 'r'
          required: false
          help: 'Absolute path to normal sample BAM files'
