---
algorithm:
  type: 'List'
  required: true
  help: 'List of sSNV algorithms'
  default:
    - mutect2
    - somaticsniper
    - strelka2
    - muse
  choices:
    - mutect2
    - somaticsniper
    - strelka2
    - muse
    - sage
reference:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Absolute path to reference directory'
reference_version:
  type: 'String'
  required: true
  help: 'Reference genome version number, e.g. 38 for GRCh38'
intersect_regions:
  type: 'Path'
  required: true
  help: 'call regions bed file used by mutect2, strelka2 and intersect'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to output directory'
work_dir:
  type: 'Path'
  mode: 'w'
  required: false
  help: 'Absolute path to output directory'
dataset_id:
  type: 'String'
  required: true
  help: 'Dataset identifier'
exome:
  type: 'Bool'
  required: false
  default: false
  help: 'The exome option when running manta and strelka2'
save_intermediate_files:
  type: 'Bool'
  required: false
  default: false
  help: 'The option to save the intermediate files'
bgzip_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for bgzip command'
tabix_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for tabix command'
split_intervals_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the SplitIntervals command'
mutect2_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the Mutect2 command'
filter_mutect_calls_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the FilterMutectCalls command'
scatter_count:
  type: 'Integer'
  required: true
germline_resource_gnomad_vcf:
  type: 'Path'
  required: false
panel_of_normals_vcf:
  type: 'Path'
  required: false
  help: 'VCF file of sites observed in a set of normal samples'
dbSNP:
  type: 'Path'
  required: true
vcf2maf_extra_args:
  type: 'String'
  required: false
  allow_empty: true
  help: 'Additional arguments for the vcf2maf command'
patient_id:
  type: 'String'
  required: true
  help: 'Patient identifier'
sage_hotspots:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to hotspots file for SAGE'
sage_panel_bed:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to panel bed file for SAGE'
sage_ensembl_data_dir:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to ensembl data directory for SAGE'
sage_high_confidence_bed:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to high confidence bed file for SAGE'
redux_unmap_regions:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to unmappable regions file for REDUX'
redux_ref_genome_msi_file:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Absolute path to reference genome MSI file for REDUX'
redux_form_consensus:
  type: 'Bool'
  required: false
  default: false
  help: 'Whether to form consensus in REDUX preprocessing'
redux_jitter_msi_only:
  type: 'Bool'
  required: false
  default: false
  help: 'Whether to use jitter MSI only mode in REDUX preprocessing'
redux_provided_ms_table_tumor:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to pre-computed tumor ms_table.tsv.gz file from REDUX, if provided will skip running REDUX'
redux_provided_ms_table_normal:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to pre-computed normal ms_table.tsv.gz file from REDUX, if provided will skip running REDUX'
redux_provided_jitter_params_tumor:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to pre-computed tumor jitter_params.tsv file from REDUX, if provided will skip running REDUX'
redux_provided_jitter_params_normal:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to pre-computed normal jitter_params.tsv file from REDUX, if provided will skip running REDUX'
redux_additional_args:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for the REDUX command'
sage_additional_args:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for the SAGE command'
sage_skip_msi_jitter:
  type: 'Bool'
  required: false
  default: false
  help: 'Whether to skip MSI jitter in SAGE variant calling'
#sage_command_mem_diff:
#  type: 'MemoryUnit'
#  required: false
#  default: '2.GB'
#  help: 'How much to subtract from the task allocated memory where the remainder is the Java heap max for SAGE processes'
base_resource_update:
  type: 'ResourceUpdateNamespace'
  required: false
  help: 'User-defined modifications for adjusting base resource allocations for processes'
  elements:
    memory:
      type: 'ResourceUpdateList'
      required: false
      help: 'List of memory updates'
    cpus:
      type: 'ResourceUpdateList'
      required: false
      help: 'List of CPU updates'
input:
  type: 'InputNamespace'
  required: true
  help: 'Input to process'
  elements:
    tumor:
      type: 'BAMEntryList'
      required: false
      help: 'Tumor id/path input'
      elements:
        BAM:
          type: 'Path'
          mode: 'r'
          required: true
          help: 'Absolute path to tumor sample BAM files'
        contamination_table:
          type: 'Path'
          mode: 'r'
          required: false
          help: 'Absolute path to contamination.tables'
    normal:
      type: 'BAMEntryList'
      required: false
      help: 'Normal id/path input'
      elements:
        BAM:
          type: 'Path'
          mode: 'r'
          required: true
          help: 'Absolute path to normal sample BAM files'
    muse:
      type: 'Path'
      mode: 'r'
      required: false
      help: 'Absolute path to muse VCF file'
    mutect2:
      type: 'Path'
      mode: 'r'
      required: false
      help: 'Absolute path to mutect2 VCF file'
    somaticsniper:
      type: 'Path'
      mode: 'r'
      required: false
      help: 'Absolute path to somaticsniper VCF file'
    strelka2:
      type: 'Path'
      mode: 'r'
      required: false
      help: 'Absolute path to strelka2 VCF file'
    sage:
      type: 'Path'
      mode: 'r'
      required: false
      help: 'Absolute path to sage VCF file'
    input_normal_id:
      type: 'String'
      required: false
      help: 'Normal id in the VCF files'
    input_tumor_id:
      type: 'String'
      required: false
      help: 'Tumor id in the VCF files'
