@startuml mutect2_chart

!include pipeline_elements.iuml!string_functions
!include pipeline_elements.iuml!input_rect
!include pipeline_elements.iuml!output_rect
!include pipeline_elements.iuml!intermediate_rect
!include pipeline_elements.iuml!qc_rect
!include pipeline_elements.iuml!process_legend

skinparam linetype ortho

$input_process(normal_bam, 'Normal BAM', 'Input: normal BAM file')
$input_process(tumor_bam, 'Tumor BAM', 'Input: tumor BAM file')
$input_process(contamination_table, 'Contamination Table: optional', 'Input: output of GATK %newline()CalculateContamination')
$input_process(reference_genome, 'Reference genome', 'Input: fasta file')
$input_process(germline_resource, 'Germline resource', 'Input: stripped gnomad VCF')

$intermediate_process(gatk_splitIntervals, 'GATK SplitIntervals', 'Output: reference genome split into %newline()params.scatter_count intervals')
$intermediate_process(mutect2_call_sSNV, 'GATK Mutect2: one process per interval', 'Output: unfiltered VCFs, variant stats, F1R2 metrics')
$intermediate_process(gatk_mergeVcfs, 'GATK MergeVcfs', 'Output: unfiltered VCF')
$intermediate_process(mutect2_mergeStats, 'GATK MergeMutectStats', 'Output: Mutect2 stats')
$intermediate_process(gatk_learnReadOrientation, 'GATK LearnReadOrientationModel', 'Output: orientation bias artifacts table')
$intermediate_process(mutect2_filterCalls, 'GATK FilterMutectCalls', 'Output: VCF with non-PASSing variants tagged %newline()Optional output: filtering stats')
$output_process(bcftools_filterVCF, 'remove non-PASS variants', 'Output: VCF including only variants that passed above filters')
$output_process(bcftools_splitVCF, 'split by variant type', 'Output: %newline()pass-snvs.vcf.gz %newline()pass-mnvs.vcf.gz %newline()pass-indels.vcf.gz')
$qc_process(gatk_filteringStats, 'Optional', 'Output: filteringStats.tsv')

reference_genome -d-> gatk_splitIntervals
normal_bam -d-> mutect2_call_sSNV
tumor_bam -d-> mutect2_call_sSNV
gatk_splitIntervals -d-> mutect2_call_sSNV
germline_resource -d-> mutect2_call_sSNV
mutect2_call_sSNV -d-> gatk_mergeVcfs
mutect2_call_sSNV -d-> gatk_learnReadOrientation
mutect2_call_sSNV -d-> mutect2_mergeStats
mutect2_call_sSNV -d-> gatk_mergeVcfs
mutect2_call_sSNV -d-> gatk_mergeVcfs
mutect2_call_sSNV -d-> gatk_learnReadOrientation
mutect2_call_sSNV -d-> mutect2_mergeStats
mutect2_call_sSNV -d-> gatk_learnReadOrientation
mutect2_call_sSNV -d-> mutect2_mergeStats

gatk_mergeVcfs -d-> mutect2_filterCalls : // unfiltered.vcf.gz //
gatk_learnReadOrientation -d-> mutect2_filterCalls : // f1r2.tar.gz //
mutect2_mergeStats -d-> mutect2_filterCalls : // unfiltered.vcf.stats.gz //
reference_genome -d-> mutect2_filterCalls
contamination_table -d-> mutect2_filterCalls
mutect2_filterCalls -d-> gatk_filteringStats
mutect2_filterCalls -d-> bcftools_filterVCF : // filtered.vcf.gz //
bcftools_filterVCF -d-> bcftools_splitVCF : // pass.vcf.gz //

$add_legend('left')

@enduml
