@startuml call_ssnv

!include pipeline_elements.iuml!string_functions
!include pipeline_elements.iuml!output_rect
!include pipeline_elements.iuml!intermediate_rect
!include pipeline_elements.iuml!qc_rect
!include pipeline_elements.iuml!process_legend

skinparam linetype ortho

$intermediate_process(normal_bam, 'Normal bam', 'input normal bam file')
$intermediate_process(tumor_bam, 'Tumor bam', 'input tumor bam file')

rectangle muse as "MusE" {
    $intermediate_process(muse_call_run, "MuSE call", "Output: position-specific %newline()summary statistics")
    $intermediate_process(dbsnp_file, 'dbSNP', 'dbSNP vcf')
    $output_process(muse_sump_run, "MuSE sump", "Output: tier-based %newline()cutoffs")

    muse_call_run -d-> muse_sump_run
    dbsnp_file -d-> muse_sump_run
}

tumor_bam -d-> muse
normal_bam -d-> muse

$add_legend("left")

@enduml
