@startuml(id=string_functions)
!unquoted function $comma_to_newline($input_str="")
!local $arg_str = ''
!foreach $item in %splitstr($input_str, ",")
    !local $arg_str = $arg_str + " %newline()" + $item
!endfor
!return %substr($arg_str, 11)
!endfunction
@enduml

@startuml(id=input_rect)
!unquoted procedure $input_process($alias, $title, $description)
rectangle $alias #LightBlue as "
$title
====
$description"
!endprocedure
@enduml

@startuml(id=intermediate_rect)
!unquoted procedure $intermediate_process($alias, $title, $description)
rectangle $alias #White as "
$title
====
$description"
!endprocedure
@enduml

@startuml(id=output_rect)
!unquoted procedure $output_process($alias, $title, $description)
rectangle $alias #LightGreen as "
$title
====
$description"
!endprocedure
@enduml

@startuml(id=qc_rect)
!unquoted procedure $qc_process($alias, $title, $description)
rectangle $alias #Yellow as "
$title
====
$description"
!endprocedure
@enduml

@startuml(id=process_legend)
!unquoted procedure $add_legend($pos="bottom right")
legend $pos
  | Color | Process Type|
  |<#LightBlue>| Input |
  |<#White>| Intermediate |
  |<#LightGreen>| Output |
  |<#Yellow>| QC |
endlegend
!endprocedure
@enduml
