@startuml muse_chart

!include pipeline_elements.iuml!string_functions
!include pipeline_elements.iuml!input_rect
!include pipeline_elements.iuml!output_rect
!include pipeline_elements.iuml!intermediate_rect
!include pipeline_elements.iuml!qc_rect
!include pipeline_elements.iuml!process_legend

skinparam linetype ortho

$input_process(normal_bam, 'Normal bam', 'input normal bam file')
$input_process(tumor_bam, 'Tumor bam', 'input tumor bam file')

$intermediate_process(muse_call_run, "MuSE call", "Output: position-specific %newline()summary statistics")
$input_process(dbsnp_file, 'dbSNP', 'dbSNP VCF')
$intermediate_process(muse_sump_run, "MuSE sump", "Output: VCF with tier-based %newline()quality cutoffs")
$output_process(filter_vcf, 'Filter VCF', 'VCF with top tier %newline()somatic variants')

tumor_bam -d-> muse_call_run
normal_bam -d-> muse_call_run
muse_call_run -d-> muse_sump_run
dbsnp_file -d-> muse_sump_run
muse_sump_run -d-> filter_vcf

$add_legend("left")

@enduml
