---
on:
  release:
    types: [published]

permissions:
  contents: write
jobs:
  add_release_asset:
    runs-on: ubuntu-latest
    name: A job to add a release asset with submodules
    steps:
      - id: release-asset
        uses: uclahs-cds/tool-Nextflow-action/add-source-with-submodules@v1
        with:
          my-token: ${{ secrets.GITHUB_TOKEN }}
