---
name: Trigger tests

on:
  issue_comment:
    types: [created]
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  pull-requests: write
  statuses: write

jobs:
  check-user:
    uses: uclahs-cds/tool-Nextflow-action/.github/workflows/test-setup.yml@main
